// <auto-generated />
using System;
using Bot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bot.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20260220044955_AddCurrentTurnToGames")]
    partial class AddCurrentTurnToGames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Bot.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentTurnId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Player1ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Player1UserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Player2ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Player2UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTurnId")
                        .IsUnique();

                    b.HasIndex("Player1ChatId", "Player1UserId");

                    b.HasIndex("Player2ChatId", "Player2UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Bot.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiceValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedDice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerChatId", "PlayerUserId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Bot.User", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId", "UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bot.Game", b =>
                {
                    b.HasOne("Bot.Turn", "CurrentTurn")
                        .WithOne()
                        .HasForeignKey("Bot.Game", "CurrentTurnId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bot.User", "Player1")
                        .WithMany("GamesAsPlayer1")
                        .HasForeignKey("Player1ChatId", "Player1UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bot.User", "Player2")
                        .WithMany("GamesAsPlayer2")
                        .HasForeignKey("Player2ChatId", "Player2UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentTurn");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("Bot.Turn", b =>
                {
                    b.HasOne("Bot.Game", "Game")
                        .WithMany("Turns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bot.User", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerChatId", "PlayerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Bot.Game", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Bot.User", b =>
                {
                    b.Navigation("GamesAsPlayer1");

                    b.Navigation("GamesAsPlayer2");
                });
#pragma warning restore 612, 618
        }
    }
}
